[package]
name = "live_kit_client"
version = "0.1.0"
edition = "2021"
description = "Logic for using LiveKit with GPUI"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/live_kit_client.rs"
doctest = false

[[example]]
name = "test_app"

[features]
no-webrtc = []
test-support = [
    "collections/test-support",
    "gpui/test-support",
    "nanoid",
]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
cpal = { git = "https://github.com/zed-industries/cpal", rev = "fd8bc2fd39f1f5fdee5a0690656caff9a26d9d50" }
collections = { workspace = true }
futures.workspace = true
gpui.workspace = true
http_2 = { package = "http", version = "0.2.1" }
live_kit_server.workspace = true
log.workspace = true
media.workspace = true
nanoid = { workspace = true, optional = true}
parking_lot.workspace = true
postage.workspace = true
util.workspace = true
http_client.workspace = true

[target.'cfg(not(target_os = "windows"))'.dependencies]
livekit.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation.workspace = true

[dev-dependencies]
collections = { workspace = true, features = ["test-support"] }
gpui = { workspace = true, features = ["test-support"] }
nanoid.workspace = true
sha2.workspace = true
simplelog.workspace = true

[build-dependencies]
serde.workspace = true
serde_json.workspace = true

[package.metadata.cargo-machete]
ignored = ["serde_json"]
